import { Router, type IRouter } from "express";
import { and, desc, eq, ilike, or, sql } from "drizzle-orm";
import { db, placementCompaniesTable, placementJobsTable, placementApplicationsTable, placementInterviewsTable, placementOffersTable, placementDrivesTable, placementDriveRegistrationsTable, placementResumesTable, alumniProfilesTable, placementMentorshipsTable, placementReferralsTable, usersTable, authSessionsTable, rolesTable, permissionsTable, rolePermissionsTable } from "@workspace/db";
import { authenticate } from "../middlewares/auth";
import { generateAssistantResponse } from "../services/aiService";
import { hashPassword, verifyPassword } from "../lib/password";
import { signToken, TOKEN_TTL_SECONDS } from "../lib/jwt";
import crypto from "node:crypto";
const router: IRouter = Router();
const placementRoles = ["super_admin", "admin", "secretary", "placement_officer", "recruiter", "student", "alumni"];
const staff = (req: any) => ["super_admin", "admin", "secretary", "placement_officer", "recruiter"].includes(req.user?.role);
const recruiter = (req: any) => ["super_admin", "admin", "placement_officer", "recruiter"].includes(req.user?.role);
const office = (req: any) => ["super_admin", "admin", "placement_officer"].includes(req.user?.role);
async function recruiterOwnsCompany(userId: number, companyId: number) {
  const [row] = await db.select({ id: placementCompaniesTable.id }).from(placementCompaniesTable)
    .where(and(eq(placementCompaniesTable.id, companyId), eq(placementCompaniesTable.ownerUserId, userId)));
  return Boolean(row);
}
async function applicationOwnedByRecruiter(userId: number, applicationId: number) {
  const [row] = await db.select({ id: placementApplicationsTable.id }).from(placementApplicationsTable)
    .innerJoin(placementJobsTable, eq(placementApplicationsTable.jobId, placementJobsTable.id))
    .innerJoin(placementCompaniesTable, eq(placementJobsTable.companyId, placementCompaniesTable.id))
    .where(and(eq(placementApplicationsTable.id, applicationId), eq(placementCompaniesTable.ownerUserId, userId)));
  return Boolean(row);
}
let rolesSeeded = false;
async function ensurePlacementRoles() {
  if (rolesSeeded) return;
  for (const role of [{ name: "placement_officer", displayName: "Placement Officer" }, { name: "recruiter", displayName: "Recruiter" }, { name: "alumni", displayName: "Alumni" }]) {
    await db.insert(rolesTable).values(role).onConflictDoNothing();
  }
  for (const permission of [
    ["placements.view", "View placements"], ["placements.manage", "Manage placements"], ["placements.recruit", "Recruiter management"],
    ["placements.reports", "Placement reports"], ["placements.alumni", "Alumni network"],
  ] as const) {
    const [row] = await db.insert(permissionsTable).values({ key: permission[0], displayName: permission[1], module: "placements", action: permission[0].split(".")[1] }).onConflictDoNothing().returning();
    if (row) {
      const targetRoles = permission[0] === "placements.recruit" ? ["recruiter", "placement_officer", "admin", "super_admin"] : ["placement_officer", "admin", "super_admin"];
      const roleRows = await db.select().from(rolesTable).where(or(...targetRoles.map((name) => eq(rolesTable.name, name))));
      await db.insert(rolePermissionsTable).values(roleRows.map((r) => ({ roleId: r.id, permissionId: row.id }))).onConflictDoNothing();
    }
  }
  rolesSeeded = true;
}
router.post("/placements/recruiters/register", async (req, res) => {
  const { name, email, password, companyName } = req.body ?? {};
  if (!name || !email || !password || !companyName) { res.status(400).json({ error: "Name, email, password, and company name are required" }); return; }
  const normalizedEmail = String(email).trim().toLowerCase();
  const [existing] = await db.select().from(usersTable).where(eq(usersTable.email, normalizedEmail));
  if (existing) { res.status(409).json({ error: "An account already exists for this email" }); return; }
  const [user] = await db.insert(usersTable).values({ name, email: normalizedEmail, passwordHash: await hashPassword(String(password)), role: "recruiter", isActive: true }).returning();
  const [company] = await db.insert(placementCompaniesTable).values({ name: companyName, email: normalizedEmail, ownerUserId: user.id, status: "pending" }).returning();
  res.status(201).json({ user: { id: user.id, name: user.name, email: user.email, role: user.role }, company });
});
router.post("/placements/recruiters/login", async (req, res) => {
  const [user] = await db.select().from(usersTable).where(and(eq(usersTable.email, String(req.body?.email ?? "").trim().toLowerCase()), eq(usersTable.role, "recruiter")));
  if (!user || !(await verifyPassword(String(req.body?.password ?? ""), user.passwordHash))) { res.status(401).json({ error: "Invalid recruiter credentials" }); return; }
  const tokenId = crypto.randomUUID();
  const token = signToken({ userId: user.id, email: user.email, role: user.role }, tokenId);
  await db.insert(authSessionsTable).values({ userId: user.id, tokenId, expiresAt: new Date(Date.now() + TOKEN_TTL_SECONDS * 1000) });
  res.json({ token, user: { id: user.id, name: user.name, email: user.email, role: user.role } });
});
router.use(authenticate);
router.use(async (_req, _res, next) => { await ensurePlacementRoles(); next(); });

router.get("/placements/dashboard", async (req, res) => {
  const applications = await db.select().from(placementApplicationsTable).where(eq(placementApplicationsTable.studentId, req.user!.userId));
  const resumes = await db.select().from(placementResumesTable).where(eq(placementResumesTable.studentId, req.user!.userId)).orderBy(desc(placementResumesTable.version));
  const interviews = await db.select().from(placementInterviewsTable).where(sql`${placementInterviewsTable.applicationId} in (select id from placement_applications where student_id = ${req.user!.userId})`);
  const offers = await db.select().from(placementOffersTable).where(sql`${placementOffersTable.applicationId} in (select id from placement_applications where student_id = ${req.user!.userId})`);
  res.json({ placementStatus: offers.length ? "Selected" : applications.length ? "In process" : "Not placed", eligibilityStatus: "Eligible", applications, interviews, offers, resumeCompletion: resumes[0]?.score ?? 0, skillsScore: resumes[0]?.score ?? 0, timeline: [] });
});
router.get("/placements/jobs", async (req, res) => {
  const q = String(req.query.q ?? "").trim();
  const jobs = await db.select({ job: placementJobsTable, company: placementCompaniesTable }).from(placementJobsTable).leftJoin(placementCompaniesTable, eq(placementJobsTable.companyId, placementCompaniesTable.id)).where(and(eq(placementJobsTable.status, "open"), q ? or(ilike(placementJobsTable.title, `%${q}%`), ilike(placementCompaniesTable.name, `%${q}%`)) : undefined)).orderBy(desc(placementJobsTable.createdAt));
  res.json(jobs);
});
router.post("/placements/applications", async (req, res) => {
  if (req.user!.role !== "student") { res.status(403).json({ error: "Student access required" }); return; }
  const [job] = await db.select().from(placementJobsTable).where(eq(placementJobsTable.id, Number(req.body.jobId)));
  if (!job) { res.status(404).json({ error: "Job not found" }); return; }
  const [existing] = await db.select().from(placementApplicationsTable).where(and(eq(placementApplicationsTable.jobId, job.id), eq(placementApplicationsTable.studentId, req.user!.userId)));
  if (existing) { res.status(409).json({ error: "Already applied" }); return; }
  res.status(201).json((await db.insert(placementApplicationsTable).values({ jobId: job.id, studentId: req.user!.userId }).returning())[0]);
});
router.patch("/placements/applications/:id", async (req, res) => { if (req.user!.role !== "student") { res.status(403).json({ error: "Student access required" }); return; } const [row] = await db.update(placementApplicationsTable).set({ status: req.body.status ?? "withdrawn" }).where(and(eq(placementApplicationsTable.id, Number(req.params.id)), eq(placementApplicationsTable.studentId, req.user!.userId))).returning(); if (!row) { res.status(404).json({ error: "Application not found" }); return; } res.json(row); });
router.get("/placements/resume", async (req, res) => res.json(await db.select().from(placementResumesTable).where(eq(placementResumesTable.studentId, req.user!.userId)).orderBy(desc(placementResumesTable.version))));
router.post("/placements/resume", async (req, res) => { const previous = await db.select().from(placementResumesTable).where(eq(placementResumesTable.studentId, req.user!.userId)).orderBy(desc(placementResumesTable.version)); const data = req.body?.data ?? req.body ?? {}; const score = Math.min(100, Object.keys(data).filter((key) => data[key]).length * 8); const [row] = await db.insert(placementResumesTable).values({ studentId: req.user!.userId, version: (previous[0]?.version ?? 0) + 1, data, score }).returning(); res.status(201).json(row); });
router.get("/placements/companies", async (req, res) => { if (!office(req) && !recruiter(req)) { res.status(403).json({ error: "Placement office access required" }); return; } res.json(await db.select().from(placementCompaniesTable).orderBy(desc(placementCompaniesTable.createdAt))); });
router.post("/placements/companies", async (req, res) => { if (!office(req)) { res.status(403).json({ error: "Placement office access required" }); return; } const [row] = await db.insert(placementCompaniesTable).values({ name: req.body.name, email: req.body.email, website: req.body.website, industry: req.body.industry, status: "pending" }).returning(); res.status(201).json(row); });
router.get("/placements/company/profile", async (req, res) => { if (!recruiter(req)) { res.status(403).json({ error: "Recruiter access required" }); return; } const [row] = await db.select().from(placementCompaniesTable).where(eq(placementCompaniesTable.ownerUserId, req.user!.userId)); res.json(row ?? null); });
router.patch("/placements/company/profile", async (req, res) => { if (!recruiter(req)) { res.status(403).json({ error: "Recruiter access required" }); return; } const updates: Record<string, unknown> = {}; for (const key of ["name", "website", "industry"]) if (req.body[key] !== undefined) updates[key] = req.body[key]; const [row] = await db.update(placementCompaniesTable).set(updates).where(eq(placementCompaniesTable.ownerUserId, req.user!.userId)).returning(); res.json(row); });
router.post("/placements/jobs", async (req, res) => { if (!recruiter(req)) { res.status(403).json({ error: "Recruiter access required" }); return; } const companyId = Number(req.body.companyId); if (req.user!.role === "recruiter" && !(await recruiterOwnsCompany(req.user!.userId, companyId))) { res.status(403).json({ error: "You do not own this company" }); return; } const [row] = await db.insert(placementJobsTable).values({ companyId, title: req.body.title, type: req.body.type ?? "placement", description: req.body.description ?? null, location: req.body.location ?? null, packageAmount: req.body.packageAmount ?? null, eligibility: req.body.eligibility ?? {}, deadline: req.body.deadline ? new Date(req.body.deadline) : null }).returning(); res.status(201).json(row); });
router.get("/placements/recruiter/dashboard", async (req, res) => { if (!recruiter(req)) { res.status(403).json({ error: "Recruiter access required" }); return; } const [company] = await db.select().from(placementCompaniesTable).where(eq(placementCompaniesTable.ownerUserId, req.user!.userId)); const jobs = company ? await db.select().from(placementJobsTable).where(eq(placementJobsTable.companyId, company.id)) : []; res.json({ company, jobs, status: company?.status ?? "pending", applications: [] }); });
router.patch("/placements/jobs/:id", async (req, res) => { if (!recruiter(req)) { res.status(403).json({ error: "Recruiter access required" }); return; } const [job] = await db.select().from(placementJobsTable).where(eq(placementJobsTable.id, Number(req.params.id))); if (!job) { res.status(404).json({ error: "Job not found" }); return; } if (req.user!.role === "recruiter") { const [company] = await db.select().from(placementCompaniesTable).where(and(eq(placementCompaniesTable.id, job.companyId), eq(placementCompaniesTable.ownerUserId, req.user!.userId))); if (!company) { res.status(403).json({ error: "You do not own this job" }); return; } } const updates: Record<string, unknown> = {}; for (const key of ["title", "type", "description", "location", "packageAmount", "status", "eligibility"]) if (req.body[key] !== undefined) updates[key] = req.body[key]; if (req.body.deadline !== undefined) updates.deadline = req.body.deadline ? new Date(req.body.deadline) : null; const [row] = await db.update(placementJobsTable).set(updates).where(eq(placementJobsTable.id, Number(req.params.id))).returning(); res.json(row); });
router.delete("/placements/jobs/:id", async (req, res) => { if (!recruiter(req)) { res.status(403).json({ error: "Recruiter access required" }); return; } const [job] = await db.select().from(placementJobsTable).where(eq(placementJobsTable.id, Number(req.params.id))); if (!job) { res.status(404).json({ error: "Job not found" }); return; } if (req.user!.role === "recruiter") { const [company] = await db.select().from(placementCompaniesTable).where(and(eq(placementCompaniesTable.id, job.companyId), eq(placementCompaniesTable.ownerUserId, req.user!.userId))); if (!company) { res.status(403).json({ error: "You do not own this job" }); return; } } await db.delete(placementJobsTable).where(eq(placementJobsTable.id, Number(req.params.id))); res.status(204).send(); });
router.get("/placements/drives", async (req, res) => { if (!office(req) && !recruiter(req)) { res.status(403).json({ error: "Placement access required" }); return; } res.json(await db.select().from(placementDrivesTable).orderBy(desc(placementDrivesTable.scheduledAt))); });
router.post("/placements/drives", async (req, res) => { if (!office(req) && !recruiter(req)) { res.status(403).json({ error: "Placement access required" }); return; } const companyId = req.body.companyId ? Number(req.body.companyId) : null; if (req.user!.role === "recruiter" && (!companyId || !(await recruiterOwnsCompany(req.user!.userId, companyId)))) { res.status(403).json({ error: "You do not own this company" }); return; } const [row] = await db.insert(placementDrivesTable).values({ companyId, title: req.body.title, scheduledAt: req.body.scheduledAt ? new Date(req.body.scheduledAt) : null }).returning(); res.status(201).json(row); });
router.patch("/placements/drives/:id", async (req, res) => { if (!office(req) && !recruiter(req)) { res.status(403).json({ error: "Placement access required" }); return; } const [drive] = await db.select().from(placementDrivesTable).where(eq(placementDrivesTable.id, Number(req.params.id))); if (!drive) { res.status(404).json({ error: "Drive not found" }); return; } if (req.user!.role === "recruiter" && (!drive.companyId || !(await recruiterOwnsCompany(req.user!.userId, drive.companyId)))) { res.status(403).json({ error: "You do not own this drive" }); return; } const [row] = await db.update(placementDrivesTable).set({ title: req.body.title, status: req.body.status, scheduledAt: req.body.scheduledAt ? new Date(req.body.scheduledAt) : undefined }).where(eq(placementDrivesTable.id, Number(req.params.id))).returning(); res.json(row); });
router.delete("/placements/drives/:id", async (req, res) => { if (!office(req) && !recruiter(req)) { res.status(403).json({ error: "Placement access required" }); return; } const [drive] = await db.select().from(placementDrivesTable).where(eq(placementDrivesTable.id, Number(req.params.id))); if (!drive) { res.status(404).json({ error: "Drive not found" }); return; } if (req.user!.role === "recruiter" && (!drive.companyId || !(await recruiterOwnsCompany(req.user!.userId, drive.companyId)))) { res.status(403).json({ error: "You do not own this drive" }); return; } await db.delete(placementDrivesTable).where(eq(placementDrivesTable.id, drive.id)); res.status(204).send(); });
router.get("/placements/drives/:id/registrations", async (req, res) => { if (!office(req) && !recruiter(req)) { res.status(403).json({ error: "Placement access required" }); return; } res.json(await db.select().from(placementDriveRegistrationsTable).where(eq(placementDriveRegistrationsTable.driveId, Number(req.params.id)))); });
router.post("/placements/drives/:id/register", async (req, res) => { if (req.user!.role !== "student") { res.status(403).json({ error: "Student access required" }); return; } const driveId = Number(req.params.id); const [drive] = await db.select().from(placementDrivesTable).where(eq(placementDrivesTable.id, driveId)); if (!drive || drive.status === "archived" || drive.status === "closed") { res.status(404).json({ error: "Drive unavailable" }); return; } const [existing] = await db.select().from(placementDriveRegistrationsTable).where(and(eq(placementDriveRegistrationsTable.driveId, driveId), eq(placementDriveRegistrationsTable.studentId, req.user!.userId))); if (existing) { res.status(409).json({ error: "Already registered", registration: existing }); return; } const [row] = await db.insert(placementDriveRegistrationsTable).values({ driveId, studentId: req.user!.userId }).returning(); res.status(201).json(row); });
router.delete("/placements/drives/:id/register", async (req, res) => { if (req.user!.role !== "student") { res.status(403).json({ error: "Student access required" }); return; } const [row] = await db.update(placementDriveRegistrationsTable).set({ status: "cancelled" }).where(and(eq(placementDriveRegistrationsTable.driveId, Number(req.params.id)), eq(placementDriveRegistrationsTable.studentId, req.user!.userId))).returning(); if (!row) { res.status(404).json({ error: "Registration not found" }); return; } res.json(row); });
router.patch("/placements/drives/:id/attendance", async (req, res) => { if (!office(req)) { res.status(403).json({ error: "Placement office access required" }); return; } const ids: number[] = Array.isArray(req.body.registrationIds) ? req.body.registrationIds.map((value: unknown) => Number(value)) : []; if (!ids.length) { res.status(400).json({ error: "registrationIds are required" }); return; } const rows = await Promise.all(ids.map((id: number) => db.update(placementDriveRegistrationsTable).set({ attendance: req.body.attendance ?? "present" }).where(and(eq(placementDriveRegistrationsTable.id, id), eq(placementDriveRegistrationsTable.driveId, Number(req.params.id)))).returning())); res.json(rows.flat()); });
router.patch("/placements/drives/:id/status", async (req, res) => { if (!office(req)) { res.status(403).json({ error: "Placement office access required" }); return; } const ids: number[] = Array.isArray(req.body.registrationIds) ? req.body.registrationIds.map((value: unknown) => Number(value)) : []; if (!ids.length) { res.status(400).json({ error: "registrationIds are required" }); return; } const rows = await Promise.all(ids.map((id: number) => db.update(placementDriveRegistrationsTable).set({ status: req.body.status }).where(and(eq(placementDriveRegistrationsTable.id, id), eq(placementDriveRegistrationsTable.driveId, Number(req.params.id)))).returning())); res.json(rows.flat()); });
router.get("/placements/eligibility", async (req, res) => { if (!office(req) && !recruiter(req)) { res.status(403).json({ error: "Placement access required" }); return; } const rows = await db.select({ user: usersTable, resume: placementResumesTable }).from(usersTable).leftJoin(placementResumesTable, eq(usersTable.id, placementResumesTable.studentId)).where(eq(usersTable.role, "student")); const skills = String(req.query.skills ?? "").toLowerCase(); const minScore = Number(req.query.resumeScore ?? 0); res.json(rows.filter((row) => (!skills || JSON.stringify(row.resume?.data ?? {}).toLowerCase().includes(skills)) && (row.resume?.score ?? 0) >= minScore).map((row) => ({ ...row.user, resumeScore: row.resume?.score ?? 0, resume: row.resume?.data ?? {} }))); });
router.get("/placements/reports", async (req, res) => { if (!office(req)) { res.status(403).json({ error: "Placement office access required" }); return; } const [{ count }] = await db.select({ count: sql<number>`count(*)` }).from(placementApplicationsTable); const [{ jobs }] = await db.select({ jobs: sql<number>`count(*)` }).from(placementJobsTable); res.json({ placementPercentage: 0, applications: Number(count), jobs: Number(jobs), highestPackage: null, averagePackage: null, companies: await db.select().from(placementCompaniesTable) }); });
router.get("/placements/export.csv", async (req, res) => { if (!office(req)) { res.status(403).json({ error: "Placement office access required" }); return; } const rows = await db.select().from(placementApplicationsTable); res.type("text/csv").send(["id,jobId,studentId,status", ...rows.map((r) => `${r.id},${r.jobId},${r.studentId},${r.status}`)].join("\n")); });
router.get("/placements/export.xlsx", async (req, res) => { if (!office(req)) { res.status(403).json({ error: "Placement office access required" }); return; } const rows = await db.select().from(placementApplicationsTable); const html = `<table><tr><th>ID</th><th>Job</th><th>Student</th><th>Status</th></tr>${rows.map((r) => `<tr><td>${r.id}</td><td>${r.jobId}</td><td>${r.studentId}</td><td>${r.status}</td></tr>`).join("")}</table>`; res.type("application/vnd.ms-excel").send(html); });
router.get("/placements/reports/departments", async (req, res) => { if (!office(req)) { res.status(403).json({ error: "Placement office access required" }); return; } res.json([]); });
router.get("/placements/reports/internships", async (req, res) => { if (!office(req)) { res.status(403).json({ error: "Placement office access required" }); return; } const rows = await db.select().from(placementJobsTable).where(eq(placementJobsTable.type, "internship")); res.json(rows); });
router.get("/placements/reports/offers", async (req, res) => { if (!office(req)) { res.status(403).json({ error: "Placement office access required" }); return; } res.json(await db.select().from(placementOffersTable)); });
router.get("/placements/analytics", async (req, res) => { if (!office(req)) { res.status(403).json({ error: "Placement office access required" }); return; } const [{ applications }] = await db.select({ applications: sql<number>`count(*)` }).from(placementApplicationsTable); const [{ offers }] = await db.select({ offers: sql<number>`count(*)` }).from(placementOffersTable); const [{ companies }] = await db.select({ companies: sql<number>`count(*)` }).from(placementCompaniesTable); const [{ jobs }] = await db.select({ jobs: sql<number>`count(*)` }).from(placementJobsTable); res.json({ placementPercentage: Number(applications) ? Math.round((Number(offers) / Number(applications)) * 100) : 0, applications: Number(applications), offers: Number(offers), companies: Number(companies), jobs: Number(jobs), hiringTrend: [], departmentPerformance: [], companyPerformance: [] }); });
router.get("/placements/notifications", async (req, res) => { if (!req.user) { res.status(401).json({ error: "Unauthorized" }); return; } res.json([]); });
router.get("/placements/offer/:id/pdf", async (req, res) => { const [offer] = await db.select().from(placementOffersTable).where(eq(placementOffersTable.id, Number(req.params.id))); if (!offer) { res.status(404).json({ error: "Offer not found" }); return; } const title = offer.offerType === "joining" ? "Joining Letter" : "Offer Letter"; const stream = `%PDF-1.4\n1 0 obj<< /Type /Catalog /Pages 2 0 R >>endobj\n2 0 obj<< /Type /Pages /Kids [3 0 R] /Count 1 >>endobj\n3 0 obj<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources<< /Font<< /F1 5 0 R >> >> >>endobj\n4 0 obj<< /Length ${title.length + 44} >>stream\nBT /F1 24 Tf 72 700 Td (${title}) Tj 0 -40 Td (Application ${offer.applicationId}) Tj ET\nendstream endobj\n5 0 obj<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>endobj\ntrailer<< /Root 1 0 R >>\n%%EOF`; res.type("application/pdf").set("Content-Disposition", `attachment; filename="${title.toLowerCase().replaceAll(" ", "-")}.pdf"`).send(stream); });
router.get("/placements/search", async (req, res) => { const q = `%${String(req.query.q ?? "").trim()}%`; const [companies, jobs, drives] = await Promise.all([db.select().from(placementCompaniesTable).where(ilike(placementCompaniesTable.name, q)).limit(20), db.select().from(placementJobsTable).where(ilike(placementJobsTable.title, q)).limit(20), db.select().from(placementDrivesTable).where(ilike(placementDrivesTable.title, q)).limit(20)]); res.json({ companies, jobs, drives }); });
router.post("/placements/ai", async (req, res) => { const result = await generateAssistantResponse({ role: req.user!.role, message: `Placement career request: ${String(req.body.prompt ?? "Provide career guidance")}` }); res.json(result); });
router.get("/placements/alumni", async (req, res) => res.json(await db.select().from(alumniProfilesTable)));
router.post("/placements/alumni/profile", async (req, res) => { const [existing] = await db.select().from(alumniProfilesTable).where(eq(alumniProfilesTable.userId, req.user!.userId)); const values = { userId: req.user!.userId, graduationYear: req.body.graduationYear ? Number(req.body.graduationYear) : null, company: req.body.company ?? null, bio: req.body.bio ?? null, mentorshipAvailable: Boolean(req.body.mentorshipAvailable) }; const [row] = existing ? await db.update(alumniProfilesTable).set(values).where(eq(alumniProfilesTable.id, existing.id)).returning() : await db.insert(alumniProfilesTable).values(values).returning(); res.status(existing ? 200 : 201).json(row); });
router.post("/placements/mentorships", async (req, res) => { const [row] = await db.insert(placementMentorshipsTable).values({ mentorId: Number(req.body.mentorId), menteeId: req.user!.userId, topic: req.body.topic ?? null }).returning(); res.status(201).json(row); });
router.patch("/placements/mentorships/:id", async (req, res) => { const [row] = await db.update(placementMentorshipsTable).set({ status: req.body.status }).where(and(eq(placementMentorshipsTable.id, Number(req.params.id)), eq(placementMentorshipsTable.mentorId, req.user!.userId))).returning(); res.json(row); });
router.get("/placements/referrals", async (req, res) => res.json(await db.select().from(placementReferralsTable).where(eq(placementReferralsTable.referrerId, req.user!.userId))));
router.post("/placements/referrals", async (req, res) => { const [row] = await db.insert(placementReferralsTable).values({ referrerId: req.user!.userId, candidateEmail: req.body.candidateEmail, companyId: req.body.companyId ? Number(req.body.companyId) : null, jobId: req.body.jobId ? Number(req.body.jobId) : null, note: req.body.note ?? null }).returning(); res.status(201).json(row); });
router.post("/placements/interviews", async (req, res) => { if (!office(req) && !recruiter(req)) { res.status(403).json({ error: "Placement access required" }); return; } const applicationId = Number(req.body.applicationId); if (req.user!.role === "recruiter" && !(await applicationOwnedByRecruiter(req.user!.userId, applicationId))) { res.status(403).json({ error: "You do not own this application" }); return; } const [row] = await db.insert(placementInterviewsTable).values({ applicationId, scheduledAt: new Date(req.body.scheduledAt), round: req.body.round ?? "Round 1" }).returning(); res.status(201).json(row); });
router.get("/placements/interviews", async (req, res) => { if (!office(req) && !recruiter(req)) { res.status(403).json({ error: "Placement access required" }); return; } res.json(await db.select().from(placementInterviewsTable).orderBy(desc(placementInterviewsTable.scheduledAt))); });
router.patch("/placements/interviews/:id", async (req, res) => { if (!office(req) && !recruiter(req)) { res.status(403).json({ error: "Placement access required" }); return; } const [interview] = await db.select().from(placementInterviewsTable).where(eq(placementInterviewsTable.id, Number(req.params.id))); if (!interview) { res.status(404).json({ error: "Interview not found" }); return; } if (req.user!.role === "recruiter" && !(await applicationOwnedByRecruiter(req.user!.userId, interview.applicationId))) { res.status(403).json({ error: "You do not own this interview" }); return; } const [row] = await db.update(placementInterviewsTable).set({ status: req.body.status, feedback: req.body.feedback, result: req.body.result, round: req.body.round }).where(eq(placementInterviewsTable.id, Number(req.params.id))).returning(); res.json(row); });
router.post("/placements/offers", async (req, res) => { if (!office(req) && !recruiter(req)) { res.status(403).json({ error: "Placement access required" }); return; } const applicationId = Number(req.body.applicationId); if (req.user!.role === "recruiter" && !(await applicationOwnedByRecruiter(req.user!.userId, applicationId))) { res.status(403).json({ error: "You do not own this application" }); return; } const type = req.body.offerType ?? "offer"; const html = req.body.documentHtml ?? `<html><body><h1>${type === "joining" ? "Joining Letter" : "Offer Letter"}</h1><p>Application ${applicationId}</p><p>Package: ${req.body.packageAmount ?? "To be discussed"}</p></body></html>`; const [row] = await db.insert(placementOffersTable).values({ applicationId, offerType: type, packageAmount: req.body.packageAmount, documentHtml: html }).returning(); res.status(201).json(row); });
router.get("/placements/offers/:id/letter", async (req, res) => { const [row] = await db.select().from(placementOffersTable).where(eq(placementOffersTable.id, Number(req.params.id))); if (!row) { res.status(404).json({ error: "Offer not found" }); return; } res.type("text/html").send(row.documentHtml ?? ""); });
export default router;