import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

export default function AdmissionTrack() {
  const [id, setId] = useState(""); const [data, setData] = useState<any>(null);
  const search = async () => { const response = await fetch(`/api/admissions/applications/${encodeURIComponent(id)}/dashboard`); setData(response.ok ? await response.json() : { error: "Application not found" }); };
  return <div className="mx-auto max-w-4xl space-y-6 px-6 py-16"><h1 className="text-3xl font-bold">Applicant dashboard</h1><div className="flex gap-2"><Input placeholder="Application ID, e.g. APP-2026-..." value={id} onChange={(e) => setId(e.target.value)} /><Button onClick={search}>Search</Button></div>{data && (data.error ? <p className="text-destructive">{data.error}</p> : <><div className="grid gap-4 md:grid-cols-3"><Card><CardHeader><CardTitle className="text-sm text-muted-foreground">Application status</CardTitle></CardHeader><CardContent><p className="text-xl font-bold capitalize">{data.application.status.replace("_"," ")}</p><p className="text-xs text-muted-foreground">{data.application.referenceNumber}</p></CardContent></Card><Card><CardHeader><CardTitle className="text-sm text-muted-foreground">Documents</CardTitle></CardHeader><CardContent><p className="text-xl font-bold">{data.documents.length} uploaded</p><p className="text-xs text-muted-foreground">{data.missingDocuments.length} missing</p></CardContent></Card><Card><CardHeader><CardTitle className="text-sm text-muted-foreground">Profile completion</CardTitle></CardHeader><CardContent><p className="text-xl font-bold">{Math.round((Object.values(data.application).filter(Boolean).length / Object.keys(data.application).length) * 100)}%</p></CardContent></Card></div><div className="grid gap-6 md:grid-cols-2"><Card><CardHeader><CardTitle>Missing documents</CardTitle></CardHeader><CardContent>{data.missingDocuments.length ? <ul className="list-disc space-y-2 pl-5 text-sm">{data.missingDocuments.map((item: string) => <li className="capitalize" key={item}>{item.replaceAll("_"," ")}</li>)}</ul> : <p className="text-sm text-emerald-600">All required documents submitted.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Timeline and notifications</CardTitle></CardHeader><CardContent className="space-y-3">{[...data.events, ...data.notifications].slice(0, 8).map((event: any) => <div className="border-l-2 border-primary pl-3 text-sm" key={`${event.id}-${event.event ?? event.template}`}><p>{event.event ?? event.subject}</p><p className="text-xs text-muted-foreground">{new Date(event.createdAt).toLocaleString()}</p></div>)}</CardContent></Card></div></>)}</div>;
}