import { useEffect, useState } from "react";
import { Activity, Archive, Bell, CalendarDays, CreditCard, KeyRound, Mail, MessageSquare, PlugZap, RefreshCw, Send, ShieldCheck, Webhook } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

const api = (path: string, init?: RequestInit) => fetch(`/api${path}`, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers || {}) } }).then(async (r) => { const body = await r.json(); if (!r.ok) throw new Error(body.error || "Request failed"); return body; });
const sections = [
  ["Connected services", PlugZap], ["Communication queues", MessageSquare], ["Payments", CreditCard], ["Calendar", CalendarDays],
  ["Jobs", RefreshCw], ["Audit logs", ShieldCheck], ["Webhooks", Webhook], ["API keys", KeyRound], ["Backups", Archive],
] as const;
export default function Integrations() {
  const [data, setData] = useState<any>(null); const [provider, setProvider] = useState("SMTP"); const [message, setMessage] = useState("");
  const load = () => api("/integrations").then(setData).catch(() => undefined);
  useEffect(() => { void load(); }, []);
  const connect = async () => { await api("/integrations/connect", { method: "POST", body: JSON.stringify({ name: `${provider} service`, provider, category: provider === "SMTP" ? "email" : "communications" }) }); await load(); };
  const queue = async () => { if (!message.trim()) return; await api("/integrations/queue", { method: "POST", body: JSON.stringify({ channel: "email", provider, recipient: "queued@university.edu", payload: { subject: "ERP integration message", body: message } }) }); setMessage(""); await load(); };
  if (!data) return <div className="p-8 text-muted-foreground">Loading integration center…</div>;
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-wider text-primary">Platform operations</p><h1 className="text-3xl font-bold tracking-tight">Integration Center</h1><p className="text-muted-foreground">Provider-neutral services, queues, jobs, security, and system health.</p></div><Button variant="outline" onClick={load}><RefreshCw className="mr-2 h-4 w-4" />Refresh status</Button></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{Object.entries(data.health).map(([key, value]) => <Card key={key}><CardContent className="pt-5"><div className="flex items-center justify-between"><span className="text-sm capitalize text-muted-foreground">{key}</span><Activity className="h-4 w-4 text-primary" /></div><p className="mt-2 text-lg font-semibold">{typeof value === "number" ? `${Math.round(value / 1024 / 1024)} MB` : String(value)}</p></CardContent></Card>)}</div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{sections.map(([title, Icon]) => <Card key={title}><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Icon className="h-4 w-4 text-primary" />{title}</CardTitle></CardHeader><CardContent><p className="text-2xl font-bold">{title === "Connected services" ? data.integrations.length : title === "Communication queues" ? data.queue.length : title === "Jobs" ? data.jobs.length : title === "Audit logs" ? data.audit.length : title === "Webhooks" ? data.webhooks.length : title === "API keys" ? data.apiKeys.length : title === "Backups" ? data.backups.length : title === "Payments" ? data.payments.length : "ICS"}</p><p className="text-sm text-muted-foreground">{title === "Calendar" ? "Calendar feed available" : "Tracked in the ERP control plane"}</p></CardContent></Card>)}</div>
    <div className="grid gap-4 lg:grid-cols-3"><Card><CardHeader><CardTitle>Connect a provider</CardTitle></CardHeader><CardContent className="flex gap-2"><Input value={provider} onChange={(e) => setProvider(e.target.value)} placeholder="SMTP, SendGrid, Stripe…" /><Button onClick={connect}>Connect</Button></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Send className="h-4 w-4" />Queue a message</CardTitle></CardHeader><CardContent className="flex gap-2"><Input value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Message payload" /><Button onClick={queue}>Queue</Button></CardContent></Card><Card><CardHeader><CardTitle>Latest activity</CardTitle></CardHeader><CardContent className="space-y-2">{data.audit.slice(0, 4).map((item: any) => <div className="flex items-center justify-between text-sm" key={item.id}><span>{item.action}</span><Badge variant="outline">logged</Badge></div>)}{!data.audit.length && <p className="text-sm text-muted-foreground">No integration activity yet.</p>}</CardContent></Card></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Bell className="h-4 w-4 text-primary" />Service readiness</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{["SMTP / SendGrid / SES / Mailgun", "Twilio / MSG91 / WhatsApp Cloud", "Razorpay / Stripe / PayPal", "Google Workspace / Microsoft 365"].map((item) => <div className="rounded-lg border p-3 text-sm" key={item}><Badge variant="secondary">Provider-neutral</Badge><p className="mt-2">{item}</p></div>)}</CardContent></Card>
  </div>;
}