import { useEffect, useMemo, useState } from "react";
import { BriefcaseBusiness, CalendarDays, Download, FileText, GraduationCap, LineChart, Search, Sparkles, Users, WandSparkles } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useAuth } from "@/contexts/AuthContext";

const api = (path: string, init?: RequestInit) => fetch(`/api${path}`, { ...init, headers: { "Content-Type": "application/json", Authorization: `Bearer ${localStorage.getItem("erp_token") || sessionStorage.getItem("erp_token")}`, ...(init?.headers || {}) } }).then(async (r) => { const body = await r.json(); if (!r.ok) throw new Error(body.error || "Request failed"); return body; });

export default function Placements() {
  const { user } = useAuth();
  const [jobs, setJobs] = useState<any[]>([]); const [dashboard, setDashboard] = useState<any>({}); const [resume, setResume] = useState<any[]>([]);
  const [query, setQuery] = useState(""); const [resumeData, setResumeData] = useState({ headline: "", skills: "", projects: "", internships: "", certifications: "", achievements: "", languages: "", socialLinks: "" }); const [ai, setAi] = useState("");
  const isStudent = user?.role === "student"; const isOffice = ["super_admin", "admin", "placement_officer"].includes(user?.role || ""); const isRecruiter = user?.role === "recruiter"; const isAlumni = user?.role === "alumni";
  const load = async () => { try { setJobs(await api(`/placements/jobs?q=${encodeURIComponent(query)}`)); } catch {} if (isStudent) { try { setDashboard(await api("/placements/dashboard")); setResume(await api("/placements/resume")); } catch {} } };
  useEffect(() => { load(); }, [query, user?.role]);
  const completion = useMemo(() => Math.min(100, Object.values(resumeData).filter(Boolean).length * 12), [resumeData]);
  const saveResume = async () => { const row = await api("/placements/resume", { method: "POST", body: JSON.stringify({ data: resumeData }) }); setResume([row, ...resume]); };
  const askAi = async () => { const result = await api("/placements/ai", { method: "POST", body: JSON.stringify({ prompt: ai || "Give me a placement preparation plan." }) }); setAi(result.content || "AI guidance generated."); };
  return <div className="space-y-6">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-2 text-primary"><BriefcaseBusiness className="h-5 w-5" /><span className="text-sm font-semibold uppercase tracking-wider">Career ecosystem</span></div><h2 className="text-3xl font-bold tracking-tight">Placement & Career Management</h2><p className="mt-1 text-muted-foreground">Connect talent, employers, and outcomes in one enterprise workspace.</p></div>{isOffice && <Button onClick={() => window.open("/api/placements/export.csv", "_blank")} variant="outline"><Download className="mr-2 h-4 w-4" />Export placement CSV</Button>}</div>
    {isStudent && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Placement status", dashboard.placementStatus || "Loading", BriefcaseBusiness], ["Eligibility", dashboard.eligibilityStatus || "Eligible", GraduationCap], ["Resume completion", `${dashboard.resumeCompletion ?? completion}%`, FileText], ["Skills score", `${dashboard.skillsScore ?? 0}/100`, LineChart]].map(([title, value, Icon]) => <Card key={title as string}><CardContent className="pt-6"><Icon className="mb-3 h-5 w-5 text-primary" /><p className="text-sm text-muted-foreground">{title as string}</p><p className="mt-1 text-2xl font-bold">{value as string}</p></CardContent></Card>)}</div></>}
    <Tabs defaultValue={isStudent ? "jobs" : "overview"}><TabsList className="flex h-auto flex-wrap"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="jobs">Jobs & Internships</TabsTrigger>{isStudent && <TabsTrigger value="resume">Resume Builder</TabsTrigger>}{isOffice && <TabsTrigger value="office">Placement Office</TabsTrigger>}{isRecruiter && <TabsTrigger value="recruiter">Recruiter Portal</TabsTrigger>}{isAlumni && <TabsTrigger value="alumni">Alumni Network</TabsTrigger>}<TabsTrigger value="ai">AI Career Coach</TabsTrigger></TabsList>
      <TabsContent value="overview"><div className="grid gap-4 md:grid-cols-3"><Card><CardHeader><CardTitle className="flex items-center gap-2"><CalendarDays className="h-5 w-5 text-primary" />Upcoming interviews</CardTitle></CardHeader><CardContent><p className="text-3xl font-bold">{dashboard.interviews?.length ?? 0}</p><p className="text-sm text-muted-foreground">Scheduled rounds</p></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><FileText className="h-5 w-5 text-primary" />Offer letters</CardTitle></CardHeader><CardContent><p className="text-3xl font-bold">{dashboard.offers?.length ?? 0}</p><p className="text-sm text-muted-foreground">Track acceptance status</p></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Users className="h-5 w-5 text-primary" />Career timeline</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">Applications, interviews, selections, and joining milestones stay connected here.</p></CardContent></Card></div></TabsContent>
      <TabsContent value="jobs"><Card><CardHeader><div className="flex flex-col justify-between gap-3 md:flex-row md:items-center"><CardTitle>Open opportunities</CardTitle><div className="relative w-full md:w-72"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input className="pl-9" placeholder="Search jobs or companies" value={query} onChange={(e) => setQuery(e.target.value)} /></div></div></CardHeader><CardContent><div className="grid gap-3">{jobs.length ? jobs.map(({ job, company }) => <div key={job.id} className="flex flex-col justify-between gap-3 rounded-xl border p-4 md:flex-row md:items-center"><div><div className="flex items-center gap-2"><h3 className="font-semibold">{job.title}</h3><Badge variant="secondary">{job.type}</Badge></div><p className="text-sm text-muted-foreground">{company?.name || "Company"} · {job.location || "Flexible"} · {job.packageAmount || "Package disclosed during process"}</p><p className="mt-1 line-clamp-2 text-sm">{job.description}</p></div>{isStudent && <Button onClick={async () => { await api("/placements/applications", { method: "POST", body: JSON.stringify({ jobId: job.id }) }); await load(); }}>Apply</Button>}</div>) : <div className="rounded-xl border border-dashed p-10 text-center text-muted-foreground">No open opportunities match your search.</div>}</div></CardContent></Card></TabsContent>
      {isStudent && <TabsContent value="resume"><Card><CardHeader><CardTitle>Enterprise Resume Builder</CardTitle><p className="text-sm text-muted-foreground">Build a versioned resume, preview it, and keep your profile placement-ready.</p></CardHeader><CardContent><div className="mb-5 rounded-lg bg-muted p-4"><div className="mb-2 flex justify-between text-sm"><span>Resume completion</span><span>{completion}%</span></div><div className="h-2 rounded-full bg-background"><div className="h-2 rounded-full bg-primary transition-all" style={{ width: `${completion}%` }} /></div></div><div className="grid gap-3 md:grid-cols-2">{Object.entries(resumeData).map(([key, value]) => <Input key={key} placeholder={key.replace(/([A-Z])/g, " $1")} value={value} onChange={(e) => setResumeData({ ...resumeData, [key]: e.target.value })} />)}</div><div className="mt-4 flex gap-2"><Button onClick={saveResume}><FileText className="mr-2 h-4 w-4" />Save new version</Button><Button variant="outline" onClick={() => window.print()}>Preview / Print PDF</Button></div><p className="mt-4 text-sm text-muted-foreground">Version history: {resume.length} saved version(s)</p></CardContent></Card></TabsContent>}
      {isOffice && <TabsContent value="office"><div className="grid gap-4 md:grid-cols-3"><Card><CardContent className="pt-6"><BriefcaseBusiness className="mb-3 h-5 w-5 text-primary" /><p className="text-sm text-muted-foreground">Applications</p><p className="text-2xl font-bold">Placement pipeline</p></CardContent></Card><Card><CardContent className="pt-6"><Users className="mb-3 h-5 w-5 text-primary" /><p className="text-sm text-muted-foreground">Companies</p><p className="text-2xl font-bold">Employer network</p></CardContent></Card><Card><CardContent className="pt-6"><LineChart className="mb-3 h-5 w-5 text-primary" /><p className="text-sm text-muted-foreground">Reports</p><p className="text-2xl font-bold">Outcome analytics</p></CardContent></Card></div></TabsContent>}
      {isRecruiter && <TabsContent value="recruiter"><Card><CardHeader><CardTitle>Recruiter portal</CardTitle></CardHeader><CardContent><p className="text-muted-foreground">Manage company profile, jobs, eligibility, campus drives, applicants, interviews, and offers from this workspace.</p></CardContent></Card></TabsContent>}
      {isAlumni && <TabsContent value="alumni"><Card><CardHeader><CardTitle>Alumni network</CardTitle></CardHeader><CardContent><p className="text-muted-foreground">Discover alumni, offer mentorship, share success stories, and create referrals.</p></CardContent></Card></TabsContent>}
      <TabsContent value="ai"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-primary" />AI Career Coach</CardTitle></CardHeader><CardContent><div className="flex gap-2"><Input value={ai} onChange={(e) => setAi(e.target.value)} placeholder="Ask for resume review, skill gaps, job matching, or interview questions" /><Button onClick={askAi}><WandSparkles className="mr-2 h-4 w-4" />Analyze</Button></div>{ai && <div className="mt-4 whitespace-pre-wrap rounded-xl bg-muted p-4 text-sm">{ai}</div>}</CardContent></Card></TabsContent>
    </Tabs>
  </div>;
}