import { useEffect, useMemo, useState } from "react";
import { BriefcaseBusiness, CalendarDays, Download, FileText, GraduationCap, LineChart, Search, Sparkles, Users, WandSparkles } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useAuth } from "@/contexts/AuthContext";

const api = (path: string, init?: RequestInit) => fetch(`/api${path}`, { ...init, headers: { "Content-Type": "application/json", Authorization: `Bearer ${localStorage.getItem("erp_token") || sessionStorage.getItem("erp_token")}`, ...(init?.headers || {}) } }).then(async (r) => { const body = await r.json(); if (!r.ok) throw new Error(body.error || "Request failed"); return body; });

export default function Placements() {
  const { user } = useAuth();
  const [jobs, setJobs] = useState<any[]>([]); const [dashboard, setDashboard] = useState<any>({}); const [resume, setResume] = useState<any[]>([]);
  const [query, setQuery] = useState(""); const [resumeData, setResumeData] = useState({ headline: "", skills: "", projects: "", internships: "", certifications: "", achievements: "", languages: "", socialLinks: "" }); const [ai, setAi] = useState("");
  const [officeData, setOfficeData] = useState<any>({ analytics: {}, drives: [], interviews: [], companies: [], notifications: [] }); const [alumni, setAlumni] = useState<any[]>([]); const [eligibility, setEligibility] = useState<any[]>([]); const [eligibilitySkills, setEligibilitySkills] = useState(""); const [driveTitle, setDriveTitle] = useState("");
  const isStudent = user?.role === "student"; const isOffice = ["super_admin", "admin", "placement_officer"].includes(user?.role || ""); const isRecruiter = user?.role === "recruiter"; const isAlumni = user?.role === "alumni";
  const load = async () => { try { setJobs(await api(`/placements/jobs?q=${encodeURIComponent(query)}`)); } catch {} if (isStudent) { try { setDashboard(await api("/placements/dashboard")); setResume(await api("/placements/resume")); } catch {} } if (isOffice) { try { const [analytics, drives, interviews, companies, notifications, eligible] = await Promise.all([api("/placements/analytics"), api("/placements/drives"), api("/placements/interviews"), api("/placements/companies"), api("/placements/notifications"), api("/placements/eligibility")]); setOfficeData({ analytics, drives, interviews, companies, notifications }); setEligibility(eligible); } catch {} } if (isRecruiter) { try { setDashboard(await api("/placements/recruiter/dashboard")); } catch {} } if (isAlumni) { try { setAlumni(await api("/placements/alumni")); } catch {} } };
  useEffect(() => { load(); }, [query, user?.role]);
  const completion = useMemo(() => Math.min(100, Object.values(resumeData).filter(Boolean).length * 12), [resumeData]);
  const saveResume = async () => { const row = await api("/placements/resume", { method: "POST", body: JSON.stringify({ data: resumeData }) }); setResume([row, ...resume]); };
  const askAi = async () => { const result = await api("/placements/ai", { method: "POST", body: JSON.stringify({ prompt: ai || "Give me a placement preparation plan." }) }); setAi(result.content || "AI guidance generated."); };
  return <div className="space-y-6">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-2 text-primary"><BriefcaseBusiness className="h-5 w-5" /><span className="text-sm font-semibold uppercase tracking-wider">Career ecosystem</span></div><h2 className="text-3xl font-bold tracking-tight">Placement & Career Management</h2><p className="mt-1 text-muted-foreground">Connect talent, employers, and outcomes in one enterprise workspace.</p></div>{isOffice && <Button onClick={() => window.open("/api/placements/export.csv", "_blank")} variant="outline"><Download className="mr-2 h-4 w-4" />Export placement CSV</Button>}</div>
    {isStudent && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Placement status", dashboard.placementStatus || "Loading", BriefcaseBusiness], ["Eligibility", dashboard.eligibilityStatus || "Eligible", GraduationCap], ["Resume completion", `${dashboard.resumeCompletion ?? completion}%`, FileText], ["Skills score", `${dashboard.skillsScore ?? 0}/100`, LineChart]].map(([title, value, Icon]) => <Card key={title as string}><CardContent className="pt-6"><Icon className="mb-3 h-5 w-5 text-primary" /><p className="text-sm text-muted-foreground">{title as string}</p><p className="mt-1 text-2xl font-bold">{value as string}</p></CardContent></Card>)}</div></>}
    <Tabs defaultValue={isStudent ? "jobs" : "overview"}><TabsList className="flex h-auto flex-wrap"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="jobs">Jobs & Internships</TabsTrigger>{isStudent && <TabsTrigger value="resume">Resume Builder</TabsTrigger>}{isOffice && <><TabsTrigger value="office">Placement Office</TabsTrigger><TabsTrigger value="drives">Campus Drives</TabsTrigger><TabsTrigger value="eligibility">Eligibility</TabsTrigger></>}{isRecruiter && <TabsTrigger value="recruiter">Recruiter Portal</TabsTrigger>}{isAlumni && <TabsTrigger value="alumni">Alumni Network</TabsTrigger>}<TabsTrigger value="ai">AI Career Coach</TabsTrigger></TabsList>
      <TabsContent value="overview"><div className="grid gap-4 md:grid-cols-3"><Card><CardHeader><CardTitle className="flex items-center gap-2"><CalendarDays className="h-5 w-5 text-primary" />Upcoming interviews</CardTitle></CardHeader><CardContent><p className="text-3xl font-bold">{dashboard.interviews?.length ?? officeData.interviews?.length ?? 0}</p><p className="text-sm text-muted-foreground">Scheduled rounds and feedback</p></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><FileText className="h-5 w-5 text-primary" />Offers</CardTitle></CardHeader><CardContent><p className="text-3xl font-bold">{dashboard.offers?.length ?? officeData.analytics?.offers ?? 0}</p><p className="text-sm text-muted-foreground">Track acceptance and joining</p></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Users className="h-5 w-5 text-primary" />Notifications</CardTitle></CardHeader><CardContent><p className="text-3xl font-bold">{officeData.notifications?.length ?? 0}</p><p className="text-sm text-muted-foreground">Recruiter, interview, and offer updates</p></CardContent></Card></div>{(isOffice || isRecruiter) && <div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Placement %", officeData.analytics?.placementPercentage ?? 0],["Active jobs", officeData.analytics?.jobs ?? dashboard.jobs?.length ?? 0],["Companies", officeData.analytics?.companies ?? officeData.companies?.length ?? 0],["Applications", officeData.analytics?.applications ?? 0]].map(([label,value]) => <Card key={label as string}><CardContent className="pt-6"><p className="text-sm text-muted-foreground">{label as string}</p><p className="mt-1 text-2xl font-bold">{String(value)}</p><div className="mt-3 h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-primary" style={{ width: `${Math.min(100, Number(value) || 0)}%` }} /></div></CardContent></Card>)}</div>}</TabsContent>
      <TabsContent value="jobs"><Card><CardHeader><div className="flex flex-col justify-between gap-3 md:flex-row md:items-center"><CardTitle>Open opportunities</CardTitle><div className="relative w-full md:w-72"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input className="pl-9" placeholder="Search jobs or companies" value={query} onChange={(e) => setQuery(e.target.value)} /></div></div></CardHeader><CardContent><div className="grid gap-3">{jobs.length ? jobs.map(({ job, company }) => <div key={job.id} className="flex flex-col justify-between gap-3 rounded-xl border p-4 md:flex-row md:items-center"><div><div className="flex items-center gap-2"><h3 className="font-semibold">{job.title}</h3><Badge variant="secondary">{job.type}</Badge></div><p className="text-sm text-muted-foreground">{company?.name || "Company"} · {job.location || "Flexible"} · {job.packageAmount || "Package disclosed during process"}</p><p className="mt-1 line-clamp-2 text-sm">{job.description}</p></div>{isStudent && <Button onClick={async () => { await api("/placements/applications", { method: "POST", body: JSON.stringify({ jobId: job.id }) }); await load(); }}>Apply</Button>}</div>) : <div className="rounded-xl border border-dashed p-10 text-center text-muted-foreground">No open opportunities match your search.</div>}</div></CardContent></Card></TabsContent>
      {isStudent && <TabsContent value="resume"><Card><CardHeader><CardTitle>Enterprise Resume Builder</CardTitle><p className="text-sm text-muted-foreground">Build a versioned resume, preview it, and keep your profile placement-ready.</p></CardHeader><CardContent><div className="mb-5 rounded-lg bg-muted p-4"><div className="mb-2 flex justify-between text-sm"><span>Resume completion</span><span>{completion}%</span></div><div className="h-2 rounded-full bg-background"><div className="h-2 rounded-full bg-primary transition-all" style={{ width: `${completion}%` }} /></div></div><div className="grid gap-3 md:grid-cols-2">{Object.entries(resumeData).map(([key, value]) => <Input key={key} placeholder={key.replace(/([A-Z])/g, " $1")} value={value} onChange={(e) => setResumeData({ ...resumeData, [key]: e.target.value })} />)}</div><div className="mt-4 flex gap-2"><Button onClick={saveResume}><FileText className="mr-2 h-4 w-4" />Save new version</Button><Button variant="outline" onClick={() => window.print()}>Preview / Print PDF</Button></div><p className="mt-4 text-sm text-muted-foreground">Version history: {resume.length} saved version(s)</p></CardContent></Card></TabsContent>}
      {isOffice && <TabsContent value="office"><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Campus drive calendar</CardTitle></CardHeader><CardContent><div className="space-y-2">{officeData.drives?.length ? officeData.drives.map((drive: any) => <div key={drive.id} className="flex items-center justify-between rounded-lg border p-3"><div><p className="font-medium">{drive.title}</p><p className="text-xs text-muted-foreground">{drive.scheduledAt ? new Date(drive.scheduledAt).toLocaleString() : "Date to be confirmed"}</p></div><Badge>{drive.status}</Badge></div>) : <p className="text-sm text-muted-foreground">No campus drives scheduled.</p>}</div></CardContent></Card><Card><CardHeader><CardTitle>Interview center</CardTitle></CardHeader><CardContent><div className="space-y-2">{officeData.interviews?.length ? officeData.interviews.map((interview: any) => <div key={interview.id} className="rounded-lg border p-3"><div className="flex justify-between"><span className="font-medium">{interview.round}</span><Badge variant="secondary">{interview.status}</Badge></div><p className="text-xs text-muted-foreground">{new Date(interview.scheduledAt).toLocaleString()}</p><p className="mt-1 text-sm">{interview.feedback || "Feedback pending"}</p></div>) : <p className="text-sm text-muted-foreground">No interviews scheduled.</p>}</div></CardContent></Card><Card><CardHeader><CardTitle>Company management</CardTitle></CardHeader><CardContent><p className="text-3xl font-bold">{officeData.companies?.length ?? 0}</p><p className="text-sm text-muted-foreground">Verified and pending employer partners</p></CardContent></Card><Card><CardHeader><CardTitle>Department performance</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">Placement, internship, offer, selection, and rejection reports are available through the report exports.</p><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => window.open("/api/placements/export.csv", "_blank")}>CSV</Button><Button size="sm" variant="outline" onClick={() => window.open("/api/placements/export.xlsx", "_blank")}>Excel</Button></div></CardContent></Card></div></TabsContent>}
      {isOffice && <TabsContent value="drives"><div className="grid gap-4 lg:grid-cols-[1fr_1.4fr]"><Card><CardHeader><CardTitle>Create campus drive</CardTitle></CardHeader><CardContent><Input placeholder="Drive title" value={driveTitle} onChange={(e) => setDriveTitle(e.target.value)} /><Button className="mt-3" onClick={async () => { if (!driveTitle.trim()) return; await api("/placements/drives", { method: "POST", body: JSON.stringify({ title: driveTitle }) }); setDriveTitle(""); await load(); }}>Create drive</Button><p className="mt-4 text-sm text-muted-foreground">Manage registration, attendance, shortlist status, capacity, and drive lifecycle from the calendar.</p></CardContent></Card><Card><CardHeader><CardTitle>Drive timeline</CardTitle></CardHeader><CardContent><div className="space-y-2">{officeData.drives?.length ? officeData.drives.map((drive: any) => <div key={drive.id} className="flex flex-col gap-2 rounded-lg border p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{drive.title}</p><p className="text-xs text-muted-foreground">{drive.scheduledAt ? new Date(drive.scheduledAt).toLocaleString() : "Schedule pending"}</p></div><div className="flex gap-2"><Badge>{drive.status}</Badge><Button size="sm" variant="outline" onClick={async () => { await api(`/placements/drives/${drive.id}`, { method: "PATCH", body: JSON.stringify({ status: drive.status === "archived" ? "planned" : "archived" }) }); await load(); }}>{drive.status === "archived" ? "Restore" : "Archive"}</Button></div></div>) : <p className="text-sm text-muted-foreground">No drives created.</p>}</div></CardContent></Card></div></TabsContent>}
      {isOffice && <TabsContent value="eligibility"><Card><CardHeader><CardTitle>Enterprise eligibility center</CardTitle><p className="text-sm text-muted-foreground">Filter students by resume score and skills, then use the resulting set for registration, shortlisting, approval, or export.</p></CardHeader><CardContent><div className="flex flex-col gap-2 sm:flex-row"><Input placeholder="Skills filter" value={eligibilitySkills} onChange={(e) => setEligibilitySkills(e.target.value)} /><Button onClick={async () => setEligibility(await api(`/placements/eligibility?skills=${encodeURIComponent(eligibilitySkills)}`))}>Filter eligible students</Button><Button variant="outline" onClick={() => window.open("/api/placements/export.csv", "_blank")}>Bulk export</Button></div><div className="mt-4 overflow-x-auto rounded-lg border"><div className="min-w-[520px]"><div className="grid grid-cols-3 border-b bg-muted p-3 text-sm font-medium"><span>Student</span><span>Email</span><span>Resume score</span></div>{eligibility.length ? eligibility.map((student: any) => <div key={student.id} className="grid grid-cols-3 border-b p-3 text-sm last:border-0"><span>{student.name || `Student #${student.id}`}</span><span>{student.email}</span><span><Badge variant="secondary">{student.resumeScore}/100</Badge></span></div>) : <p className="p-6 text-center text-sm text-muted-foreground">No eligible students match the current filters.</p>}</div></div></CardContent></Card></TabsContent>}
      {isRecruiter && <TabsContent value="recruiter"><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Company profile</CardTitle></CardHeader><CardContent><p className="text-2xl font-bold">{dashboard.company?.name || "Company pending verification"}</p><p className="text-sm text-muted-foreground">{dashboard.company?.industry || "Industry not set"} · {dashboard.status || "pending"}</p><p className="mt-4 text-sm text-muted-foreground">Manage your company profile, active and closed jobs, campus drives, applicant pipeline, interviews, and offers.</p></CardContent></Card><Card><CardHeader><CardTitle>Hiring statistics</CardTitle></CardHeader><CardContent><div className="grid grid-cols-3 gap-3 text-center"><div><p className="text-2xl font-bold">{dashboard.jobs?.filter((job: any) => job.status === "open").length ?? 0}</p><p className="text-xs text-muted-foreground">Active jobs</p></div><div><p className="text-2xl font-bold">{dashboard.jobs?.filter((job: any) => job.status !== "open").length ?? 0}</p><p className="text-xs text-muted-foreground">Closed jobs</p></div><div><p className="text-2xl font-bold">{dashboard.applications?.length ?? 0}</p><p className="text-xs text-muted-foreground">Applications</p></div></div></CardContent></Card><Card className="lg:col-span-2"><CardHeader><CardTitle>Quick actions</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2"><Button onClick={() => setQuery("")}>Browse talent opportunities</Button><Button variant="outline" onClick={() => window.open("/placements/recruiter", "_self")}>Company settings</Button><Button variant="outline">Schedule interview round</Button><Button variant="outline">Create offer letter</Button></CardContent></Card></div></TabsContent>}
      {isAlumni && <TabsContent value="alumni"><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Alumni directory</CardTitle></CardHeader><CardContent><div className="space-y-2">{alumni.length ? alumni.map((profile: any) => <div key={profile.id} className="rounded-lg border p-3"><p className="font-medium">{profile.company || "Career history available"}</p><p className="text-sm text-muted-foreground">{profile.graduationYear || "Graduate"} · {profile.mentorshipAvailable ? "Mentorship available" : "Networking profile"}</p></div>) : <p className="text-sm text-muted-foreground">No alumni profiles published yet.</p>}</div></CardContent></Card><Card><CardHeader><CardTitle>Mentorship & referrals</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">Offer mentorship, submit company referrals, share success stories, and build professional connections with students and alumni.</p><div className="mt-4 flex flex-wrap gap-2"><Button>Offer mentorship</Button><Button variant="outline">Submit referral</Button><Button variant="outline">Share success story</Button></div></CardContent></Card></div></TabsContent>}
      <TabsContent value="ai"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-primary" />AI Career Coach</CardTitle></CardHeader><CardContent><div className="flex gap-2"><Input value={ai} onChange={(e) => setAi(e.target.value)} placeholder="Ask for resume review, skill gaps, job matching, or interview questions" /><Button onClick={askAi}><WandSparkles className="mr-2 h-4 w-4" />Analyze</Button></div>{ai && <div className="mt-4 whitespace-pre-wrap rounded-xl bg-muted p-4 text-sm">{ai}</div>}</CardContent></Card></TabsContent>
    </Tabs>
  </div>;
}